[package]
name = "ownrs-cli"
version = "0.1.0"
authors = ["Josh Leeb-du Toit <mail@joshleeb.com>"]
edition = "2018"
public = false

[dependencies]
clap = "2.32.0"
ownrs = "0.1.0"

[[bin]]
name = "ownrs"
path = "src/main.rs"
